// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.Empty)
    com.google.protobuf.MessageOrBuilder {
}
