// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public interface ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 itemID = 1;</code>
   * @return The itemID.
   */
  int getItemID();

  /**
   * <code>string itemName = 2;</code>
   * @return The itemName.
   */
  java.lang.String getItemName();
  /**
   * <code>string itemName = 2;</code>
   * @return The bytes for itemName.
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>int32 price = 3;</code>
   * @return The price.
   */
  int getPrice();
}
