// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderID = 1;</code>
   * @return The orderID.
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 1;</code>
   * @return The bytes for orderID.
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();

  /**
   * <code>string orderDate = 2;</code>
   * @return The orderDate.
   */
  java.lang.String getOrderDate();
  /**
   * <code>string orderDate = 2;</code>
   * @return The bytes for orderDate.
   */
  com.google.protobuf.ByteString
      getOrderDateBytes();

  /**
   * <code>int32 amount = 3;</code>
   * @return The amount.
   */
  int getAmount();

  /**
   * <code>int32 orderItemCount = 4;</code>
   * @return The orderItemCount.
   */
  int getOrderItemCount();

  /**
   * <code>.order.Status orderStatus = 5;</code>
   * @return The enum numeric value on the wire for orderStatus.
   */
  int getOrderStatusValue();
  /**
   * <code>.order.Status orderStatus = 5;</code>
   * @return The orderStatus.
   */
  com.cybage.order.Status getOrderStatus();
}
