// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\005order\032\nuser.proto\"7\n\004Item" +
      "\022\016\n\006itemID\030\001 \001(\005\022\020\n\010itemName\030\002 \001(\t\022\r\n\005pr" +
      "ice\030\003 \001(\005\"*\n\014OrderRequest\022\032\n\005items\030\001 \003(\013" +
      "2\013.order.Item\"\007\n\005Empty\"\310\001\n\rOrderResponse" +
      "\022\017\n\007orderID\030\001 \001(\t\022\021\n\torderDate\030\002 \001(\t\022\016\n\006" +
      "amount\030\003 \001(\005\022\032\n\005items\030\004 \003(\0132\013.order.Item" +
      "\022\026\n\016orderItemCount\030\005 \001(\005\022\"\n\013orderStatus\030" +
      "\006 \001(\0162\r.order.Status\022+\n\rpaymentStatus\030\007 " +
      "\001(\0162\024.order.PaymentStatus*?\n\006Status\022\013\n\007P" +
      "ENDING\020\000\022\017\n\013IN_PROGRESS\020\001\022\013\n\007SUCCESS\020\002\022\n" +
      "\n\006FAILED\020\003*%\n\rPaymentStatus\022\010\n\004PAID\020\000\022\n\n" +
      "\006UNPAID\020\0012y\n\014OrderService\0227\n\nplaceOrder\022" +
      "\023.order.OrderRequest\032\024.order.OrderRespon" +
      "se\0220\n\010getOrder\022\014.order.Empty\032\024.order.Ord" +
      "erResponse0\001B\024\n\020com.cybage.orderP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cybage.grpc.User.getDescriptor(),
        });
    internal_static_order_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_Item_descriptor,
        new java.lang.String[] { "ItemID", "ItemName", "Price", });
    internal_static_order_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderRequest_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_order_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_order_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_order_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderResponse_descriptor,
        new java.lang.String[] { "OrderID", "OrderDate", "Amount", "Items", "OrderItemCount", "OrderStatus", "PaymentStatus", });
    com.cybage.grpc.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
