// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public final class OrderOuterClass {
  private OrderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\005order\"w\n\005Order\022\017\n\007orderID" +
      "\030\001 \001(\t\022\021\n\torderDate\030\002 \001(\t\022\016\n\006amount\030\003 \001(" +
      "\005\022\026\n\016orderItemCount\030\004 \001(\005\022\"\n\013orderStatus" +
      "\030\005 \001(\0162\r.order.Status*?\n\006Status\022\013\n\007PENDI" +
      "NG\020\000\022\017\n\013IN_PROGRESS\020\001\022\013\n\007SUCCESS\020\002\022\n\n\006FA" +
      "ILED\020\003B\024\n\020com.cybage.orderP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_order_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_Order_descriptor,
        new java.lang.String[] { "OrderID", "OrderDate", "Amount", "OrderItemCount", "OrderStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
