// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

/**
 * Protobuf type {@code order.OrderResponse}
 */
public  final class OrderResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.OrderResponse)
    OrderResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderResponse.newBuilder() to construct.
  private OrderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderResponse() {
    orderID_ = "";
    orderDate_ = "";
    items_ = java.util.Collections.emptyList();
    orderStatus_ = 0;
    paymentStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            orderID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            orderDate_ = s;
            break;
          }
          case 24: {

            amount_ = input.readInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<com.cybage.order.Item>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(com.cybage.order.Item.parser(), extensionRegistry));
            break;
          }
          case 40: {

            orderItemCount_ = input.readInt32();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            orderStatus_ = rawValue;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            paymentStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cybage.order.Order.internal_static_order_OrderResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cybage.order.Order.internal_static_order_OrderResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cybage.order.OrderResponse.class, com.cybage.order.OrderResponse.Builder.class);
  }

  public static final int ORDERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object orderID_;
  /**
   * <code>string orderID = 1;</code>
   * @return The orderID.
   */
  public java.lang.String getOrderID() {
    java.lang.Object ref = orderID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderID_ = s;
      return s;
    }
  }
  /**
   * <code>string orderID = 1;</code>
   * @return The bytes for orderID.
   */
  public com.google.protobuf.ByteString
      getOrderIDBytes() {
    java.lang.Object ref = orderID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERDATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object orderDate_;
  /**
   * <code>string orderDate = 2;</code>
   * @return The orderDate.
   */
  public java.lang.String getOrderDate() {
    java.lang.Object ref = orderDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderDate_ = s;
      return s;
    }
  }
  /**
   * <code>string orderDate = 2;</code>
   * @return The bytes for orderDate.
   */
  public com.google.protobuf.ByteString
      getOrderDateBytes() {
    java.lang.Object ref = orderDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private int amount_;
  /**
   * <code>int32 amount = 3;</code>
   * @return The amount.
   */
  public int getAmount() {
    return amount_;
  }

  public static final int ITEMS_FIELD_NUMBER = 4;
  private java.util.List<com.cybage.order.Item> items_;
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  public java.util.List<com.cybage.order.Item> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  public java.util.List<? extends com.cybage.order.ItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  public com.cybage.order.Item getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  public com.cybage.order.ItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int ORDERITEMCOUNT_FIELD_NUMBER = 5;
  private int orderItemCount_;
  /**
   * <code>int32 orderItemCount = 5;</code>
   * @return The orderItemCount.
   */
  public int getOrderItemCount() {
    return orderItemCount_;
  }

  public static final int ORDERSTATUS_FIELD_NUMBER = 6;
  private int orderStatus_;
  /**
   * <code>.order.Status orderStatus = 6;</code>
   * @return The enum numeric value on the wire for orderStatus.
   */
  public int getOrderStatusValue() {
    return orderStatus_;
  }
  /**
   * <code>.order.Status orderStatus = 6;</code>
   * @return The orderStatus.
   */
  public com.cybage.order.Status getOrderStatus() {
    @SuppressWarnings("deprecation")
    com.cybage.order.Status result = com.cybage.order.Status.valueOf(orderStatus_);
    return result == null ? com.cybage.order.Status.UNRECOGNIZED : result;
  }

  public static final int PAYMENTSTATUS_FIELD_NUMBER = 7;
  private int paymentStatus_;
  /**
   * <code>.order.PaymentStatus paymentStatus = 7;</code>
   * @return The enum numeric value on the wire for paymentStatus.
   */
  public int getPaymentStatusValue() {
    return paymentStatus_;
  }
  /**
   * <code>.order.PaymentStatus paymentStatus = 7;</code>
   * @return The paymentStatus.
   */
  public com.cybage.order.PaymentStatus getPaymentStatus() {
    @SuppressWarnings("deprecation")
    com.cybage.order.PaymentStatus result = com.cybage.order.PaymentStatus.valueOf(paymentStatus_);
    return result == null ? com.cybage.order.PaymentStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOrderIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderID_);
    }
    if (!getOrderDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderDate_);
    }
    if (amount_ != 0) {
      output.writeInt32(3, amount_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(4, items_.get(i));
    }
    if (orderItemCount_ != 0) {
      output.writeInt32(5, orderItemCount_);
    }
    if (orderStatus_ != com.cybage.order.Status.PENDING.getNumber()) {
      output.writeEnum(6, orderStatus_);
    }
    if (paymentStatus_ != com.cybage.order.PaymentStatus.PAID.getNumber()) {
      output.writeEnum(7, paymentStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOrderIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderID_);
    }
    if (!getOrderDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderDate_);
    }
    if (amount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, amount_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, items_.get(i));
    }
    if (orderItemCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, orderItemCount_);
    }
    if (orderStatus_ != com.cybage.order.Status.PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, orderStatus_);
    }
    if (paymentStatus_ != com.cybage.order.PaymentStatus.PAID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, paymentStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cybage.order.OrderResponse)) {
      return super.equals(obj);
    }
    com.cybage.order.OrderResponse other = (com.cybage.order.OrderResponse) obj;

    if (!getOrderID()
        .equals(other.getOrderID())) return false;
    if (!getOrderDate()
        .equals(other.getOrderDate())) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (getOrderItemCount()
        != other.getOrderItemCount()) return false;
    if (orderStatus_ != other.orderStatus_) return false;
    if (paymentStatus_ != other.paymentStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderID().hashCode();
    hash = (37 * hash) + ORDERDATE_FIELD_NUMBER;
    hash = (53 * hash) + getOrderDate().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + ORDERITEMCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getOrderItemCount();
    hash = (37 * hash) + ORDERSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + orderStatus_;
    hash = (37 * hash) + PAYMENTSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + paymentStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cybage.order.OrderResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cybage.order.OrderResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cybage.order.OrderResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cybage.order.OrderResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cybage.order.OrderResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cybage.order.OrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cybage.order.OrderResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.OrderResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.OrderResponse)
      com.cybage.order.OrderResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cybage.order.Order.internal_static_order_OrderResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cybage.order.Order.internal_static_order_OrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cybage.order.OrderResponse.class, com.cybage.order.OrderResponse.Builder.class);
    }

    // Construct using com.cybage.order.OrderResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      orderID_ = "";

      orderDate_ = "";

      amount_ = 0;

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      orderItemCount_ = 0;

      orderStatus_ = 0;

      paymentStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cybage.order.Order.internal_static_order_OrderResponse_descriptor;
    }

    @java.lang.Override
    public com.cybage.order.OrderResponse getDefaultInstanceForType() {
      return com.cybage.order.OrderResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cybage.order.OrderResponse build() {
      com.cybage.order.OrderResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cybage.order.OrderResponse buildPartial() {
      com.cybage.order.OrderResponse result = new com.cybage.order.OrderResponse(this);
      int from_bitField0_ = bitField0_;
      result.orderID_ = orderID_;
      result.orderDate_ = orderDate_;
      result.amount_ = amount_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.orderItemCount_ = orderItemCount_;
      result.orderStatus_ = orderStatus_;
      result.paymentStatus_ = paymentStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cybage.order.OrderResponse) {
        return mergeFrom((com.cybage.order.OrderResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cybage.order.OrderResponse other) {
      if (other == com.cybage.order.OrderResponse.getDefaultInstance()) return this;
      if (!other.getOrderID().isEmpty()) {
        orderID_ = other.orderID_;
        onChanged();
      }
      if (!other.getOrderDate().isEmpty()) {
        orderDate_ = other.orderDate_;
        onChanged();
      }
      if (other.getAmount() != 0) {
        setAmount(other.getAmount());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.getOrderItemCount() != 0) {
        setOrderItemCount(other.getOrderItemCount());
      }
      if (other.orderStatus_ != 0) {
        setOrderStatusValue(other.getOrderStatusValue());
      }
      if (other.paymentStatus_ != 0) {
        setPaymentStatusValue(other.getPaymentStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cybage.order.OrderResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cybage.order.OrderResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object orderID_ = "";
    /**
     * <code>string orderID = 1;</code>
     * @return The orderID.
     */
    public java.lang.String getOrderID() {
      java.lang.Object ref = orderID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orderID = 1;</code>
     * @return The bytes for orderID.
     */
    public com.google.protobuf.ByteString
        getOrderIDBytes() {
      java.lang.Object ref = orderID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderID = 1;</code>
     * @param value The orderID to set.
     * @return This builder for chaining.
     */
    public Builder setOrderID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orderID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderID() {
      
      orderID_ = getDefaultInstance().getOrderID();
      onChanged();
      return this;
    }
    /**
     * <code>string orderID = 1;</code>
     * @param value The bytes for orderID to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object orderDate_ = "";
    /**
     * <code>string orderDate = 2;</code>
     * @return The orderDate.
     */
    public java.lang.String getOrderDate() {
      java.lang.Object ref = orderDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orderDate = 2;</code>
     * @return The bytes for orderDate.
     */
    public com.google.protobuf.ByteString
        getOrderDateBytes() {
      java.lang.Object ref = orderDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderDate = 2;</code>
     * @param value The orderDate to set.
     * @return This builder for chaining.
     */
    public Builder setOrderDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orderDate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderDate() {
      
      orderDate_ = getDefaultInstance().getOrderDate();
      onChanged();
      return this;
    }
    /**
     * <code>string orderDate = 2;</code>
     * @param value The bytes for orderDate to set.
     * @return This builder for chaining.
     */
    public Builder setOrderDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderDate_ = value;
      onChanged();
      return this;
    }

    private int amount_ ;
    /**
     * <code>int32 amount = 3;</code>
     * @return The amount.
     */
    public int getAmount() {
      return amount_;
    }
    /**
     * <code>int32 amount = 3;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(int value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.cybage.order.Item> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.cybage.order.Item>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cybage.order.Item, com.cybage.order.Item.Builder, com.cybage.order.ItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public java.util.List<com.cybage.order.Item> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public com.cybage.order.Item getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder setItems(
        int index, com.cybage.order.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder setItems(
        int index, com.cybage.order.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder addItems(com.cybage.order.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder addItems(
        int index, com.cybage.order.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder addItems(
        com.cybage.order.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder addItems(
        int index, com.cybage.order.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.cybage.order.Item> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public com.cybage.order.Item.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public com.cybage.order.ItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public java.util.List<? extends com.cybage.order.ItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public com.cybage.order.Item.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.cybage.order.Item.getDefaultInstance());
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public com.cybage.order.Item.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.cybage.order.Item.getDefaultInstance());
    }
    /**
     * <code>repeated .order.Item items = 4;</code>
     */
    public java.util.List<com.cybage.order.Item.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cybage.order.Item, com.cybage.order.Item.Builder, com.cybage.order.ItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cybage.order.Item, com.cybage.order.Item.Builder, com.cybage.order.ItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private int orderItemCount_ ;
    /**
     * <code>int32 orderItemCount = 5;</code>
     * @return The orderItemCount.
     */
    public int getOrderItemCount() {
      return orderItemCount_;
    }
    /**
     * <code>int32 orderItemCount = 5;</code>
     * @param value The orderItemCount to set.
     * @return This builder for chaining.
     */
    public Builder setOrderItemCount(int value) {
      
      orderItemCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 orderItemCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderItemCount() {
      
      orderItemCount_ = 0;
      onChanged();
      return this;
    }

    private int orderStatus_ = 0;
    /**
     * <code>.order.Status orderStatus = 6;</code>
     * @return The enum numeric value on the wire for orderStatus.
     */
    public int getOrderStatusValue() {
      return orderStatus_;
    }
    /**
     * <code>.order.Status orderStatus = 6;</code>
     * @param value The enum numeric value on the wire for orderStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOrderStatusValue(int value) {
      orderStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.order.Status orderStatus = 6;</code>
     * @return The orderStatus.
     */
    public com.cybage.order.Status getOrderStatus() {
      @SuppressWarnings("deprecation")
      com.cybage.order.Status result = com.cybage.order.Status.valueOf(orderStatus_);
      return result == null ? com.cybage.order.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.order.Status orderStatus = 6;</code>
     * @param value The orderStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOrderStatus(com.cybage.order.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      orderStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.order.Status orderStatus = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderStatus() {
      
      orderStatus_ = 0;
      onChanged();
      return this;
    }

    private int paymentStatus_ = 0;
    /**
     * <code>.order.PaymentStatus paymentStatus = 7;</code>
     * @return The enum numeric value on the wire for paymentStatus.
     */
    public int getPaymentStatusValue() {
      return paymentStatus_;
    }
    /**
     * <code>.order.PaymentStatus paymentStatus = 7;</code>
     * @param value The enum numeric value on the wire for paymentStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentStatusValue(int value) {
      paymentStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.order.PaymentStatus paymentStatus = 7;</code>
     * @return The paymentStatus.
     */
    public com.cybage.order.PaymentStatus getPaymentStatus() {
      @SuppressWarnings("deprecation")
      com.cybage.order.PaymentStatus result = com.cybage.order.PaymentStatus.valueOf(paymentStatus_);
      return result == null ? com.cybage.order.PaymentStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.order.PaymentStatus paymentStatus = 7;</code>
     * @param value The paymentStatus to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentStatus(com.cybage.order.PaymentStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      paymentStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.order.PaymentStatus paymentStatus = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentStatus() {
      
      paymentStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:order.OrderResponse)
  }

  // @@protoc_insertion_point(class_scope:order.OrderResponse)
  private static final com.cybage.order.OrderResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cybage.order.OrderResponse();
  }

  public static com.cybage.order.OrderResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderResponse>
      PARSER = new com.google.protobuf.AbstractParser<OrderResponse>() {
    @java.lang.Override
    public OrderResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cybage.order.OrderResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

