// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderID = 1;</code>
   * @return The orderID.
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 1;</code>
   * @return The bytes for orderID.
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();

  /**
   * <code>string orderDate = 2;</code>
   * @return The orderDate.
   */
  java.lang.String getOrderDate();
  /**
   * <code>string orderDate = 2;</code>
   * @return The bytes for orderDate.
   */
  com.google.protobuf.ByteString
      getOrderDateBytes();

  /**
   * <code>int32 amount = 3;</code>
   * @return The amount.
   */
  int getAmount();

  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  java.util.List<com.cybage.order.Item> 
      getItemsList();
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  com.cybage.order.Item getItems(int index);
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  java.util.List<? extends com.cybage.order.ItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .order.Item items = 4;</code>
   */
  com.cybage.order.ItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>int32 orderItemCount = 5;</code>
   * @return The orderItemCount.
   */
  int getOrderItemCount();

  /**
   * <code>.order.Status orderStatus = 6;</code>
   * @return The enum numeric value on the wire for orderStatus.
   */
  int getOrderStatusValue();
  /**
   * <code>.order.Status orderStatus = 6;</code>
   * @return The orderStatus.
   */
  com.cybage.order.Status getOrderStatus();

  /**
   * <code>.order.PaymentStatus paymentStatus = 7;</code>
   * @return The enum numeric value on the wire for paymentStatus.
   */
  int getPaymentStatusValue();
  /**
   * <code>.order.PaymentStatus paymentStatus = 7;</code>
   * @return The paymentStatus.
   */
  com.cybage.order.PaymentStatus getPaymentStatus();
}
