// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.cybage.order;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order.Item items = 1;</code>
   */
  java.util.List<com.cybage.order.Item> 
      getItemsList();
  /**
   * <code>repeated .order.Item items = 1;</code>
   */
  com.cybage.order.Item getItems(int index);
  /**
   * <code>repeated .order.Item items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .order.Item items = 1;</code>
   */
  java.util.List<? extends com.cybage.order.ItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .order.Item items = 1;</code>
   */
  com.cybage.order.ItemOrBuilder getItemsOrBuilder(
      int index);
}
