// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecommerce.proto

package com.cybage.ecommerce;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ecommerce.Category orderCategory = 1;</code>
   * @return The enum numeric value on the wire for orderCategory.
   */
  int getOrderCategoryValue();
  /**
   * <code>.ecommerce.Category orderCategory = 1;</code>
   * @return The orderCategory.
   */
  com.cybage.ecommerce.Category getOrderCategory();
}
