// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ecommerce.proto

package com.cybage.ecommerce;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ecommerce.Status orderStatus = 1;</code>
   * @return The enum numeric value on the wire for orderStatus.
   */
  int getOrderStatusValue();
  /**
   * <code>.ecommerce.Status orderStatus = 1;</code>
   * @return The orderStatus.
   */
  com.cybage.ecommerce.Status getOrderStatus();
}
